# like grokloc-deno:base, except files are copied in instead of mounted
# the image created is used to run tests in through ci
FROM grokloc/grokloc-deno:base
WORKDIR /grokloc
ENV GROKLOC_ENV UNIT
COPY deno.json deno.json
COPY env env
COPY lib lib
COPY main.ts main.ts
CMD ["tail", "-f", "/dev/null"]
